//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoVirtualSql
{
    using System;
    
    public partial class EXTRATO_Result1
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public string VALOR { get; set; }
        public Nullable<System.DateTime> DATA_E_HORA { get; set; }
    }
}
