//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoVirtualSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoVirtualEntities1 : DbContext
    {
        public BancoVirtualEntities1()
            : base("name=BancoVirtualEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SACAR(string aGENCIA, string cONTA, Nullable<decimal> vALOR)
        {
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SACAR", aGENCIAParameter, cONTAParameter, vALORParameter);
        }
    
        public virtual int DEPOSITAR(string aGENCIA, string cONTA, Nullable<decimal> vALOR)
        {
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEPOSITAR", aGENCIAParameter, cONTAParameter, vALORParameter);
        }
    
        public virtual int PAGAR(string aGENCIA, string cONTA, Nullable<decimal> vALOR, string tIPO)
        {
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PAGAR", aGENCIAParameter, cONTAParameter, vALORParameter, tIPOParameter);
        }
    
        public virtual int TRANSFERIR(string aGENCIA, string cONTA, string aGENCIACLI, string cONTACLI, Nullable<decimal> vALOR)
        {
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            var aGENCIACLIParameter = aGENCIACLI != null ?
                new ObjectParameter("AGENCIACLI", aGENCIACLI) :
                new ObjectParameter("AGENCIACLI", typeof(string));
    
            var cONTACLIParameter = cONTACLI != null ?
                new ObjectParameter("CONTACLI", cONTACLI) :
                new ObjectParameter("CONTACLI", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRANSFERIR", aGENCIAParameter, cONTAParameter, aGENCIACLIParameter, cONTACLIParameter, vALORParameter);
        }
    
        public virtual ObjectResult<EXTRATO_Result1> EXTRATO(string aGENCIA, string cONTA)
        {
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EXTRATO_Result1>("EXTRATO", aGENCIAParameter, cONTAParameter);
        }
    }
}
