//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoVirtualSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoVirtualEntities : DbContext
    {
        public BancoVirtualEntities()
            : base("name=BancoVirtualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SACAR(Nullable<int> iD_CLIENTE, string aGENCIA, string cONTA, Nullable<decimal> vALOR)
        {
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(int));
    
            var aGENCIAParameter = aGENCIA != null ?
                new ObjectParameter("AGENCIA", aGENCIA) :
                new ObjectParameter("AGENCIA", typeof(string));
    
            var cONTAParameter = cONTA != null ?
                new ObjectParameter("CONTA", cONTA) :
                new ObjectParameter("CONTA", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SACAR", iD_CLIENTEParameter, aGENCIAParameter, cONTAParameter, vALORParameter);
        }
    }
}
